modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "untitledduckmod"
version = "${version}"
displayName = "Untitled Duck Mod"
authors = "Paspartout, ArtistMonster24"
logoFile = "logo.png"
credits = "Thanks to geckolib!"
description = '''
Ducks for Forge and Fabric! Powered by geckolib and architectury.
'''

[[dependencies.untitledduckmod]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.untitledduckmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.untitledduckmod]]
modId="geckolib3"
mandatory=true
versionRange="[3.0.28,)"
ordering="NONE"
side="BOTH"

