modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/Okabintaro/UntitledDuckMod/issues"
license = "MIT"

[[mods]]
modId = "untitledduckmod"
version = "${version}"
displayName = "Untitled Duck Mod"
authors = "Okabintaro, ArtistMonster24"
logoFile = "logo.png"
credits = "Thanks to geckolib and architectury!"
description = '''
Ducks and Geese for Forge and Fabric! Powered by geckolib and architectury.
'''

[[dependencies.untitledduckmod]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.untitledduckmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.untitledduckmod]]
modId="geckolib3"
mandatory=true
versionRange="[3.1.14,)"
ordering="NONE"
side="BOTH"

